"""empty message

Revision ID: ce12e228eeea
Revises: 7542244866ed
Create Date: 2017-12-20 00:04:11.089524

"""

# revision identifiers, used by Alembic.
revision = 'ce12e228eeea'
down_revision = '7542244866ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
